### ISSUE TITLE
 Could you release a windows executable that includes Python？

### ISSUE THREAD

**Issue by stroop566** [kensanata/mastodon-backup#42]
use PyInstaller or py2exe, just like [youtube-dl](http://rg3.github.io/youtube-dl/).
so I can use it in cmd:
```
$ mastodon-archive.exe text kensanata@dice.camp > statuses.txt
$ mastodon-archive html kensanata@dice.camp
```
References:
1. https://medium.com/dreamcatcher-its-blog/making-an-stand-alone-executable-from-a-python-script-using-pyinstaller-d1df9170e263
2. https://stackoverflow.com/questions/5458048/how-to-make-a-python-script-standalone-executable-to-run-without-any-dependency
thank you!

**Comment by kensanata** [comment]
Do think you could write the necessary code? I only have access to a windows machine at the office.

**Comment by stroop566** [comment]
sorry,I'm a teacher,my coding ability is poor.
but you can try vmware or virtualbox.

> What you can do is run Virtualbox or similar application to run the OS virtually and, create executable in that virtual os and export it later. Also, Wine works as well! (Though, I didn’t try it myself)

thank you much more.

**Comment by BartG95** [comment]
I can probably help out. I currently have a windows machine. It will only allow me start this project, because I plan switch to a non-windows system soon-ish. So after that, someone has to maintain it. Maintenance shouldn't be very difficult for a non-coder. I can probably set up a manual.

**Comment by kensanata** [comment]
Perfect, thanks!

**Comment by stroop566** [comment]
thanks all ：）

**Comment by BartG95** [comment]
After two hours of trying, this is my conclusion:
* pyinstaller doesn't work: it can not find the main module, therefore doesn't include it in the final .exe.
* py2exe (used by youtube-dl) only works on python 3.4. I have python 3.7 installed. I could of course install 3.4 side-by-side, but p2exe isn't updated in the last 5 years and I don't see why I would install such old software.

I will probably try again in about a few days, but as for now, I wasted to many hours on this.
Sorry ;)
Have a nice weekend.

**Comment by kensanata** [comment]
Thank you anyway!

**Comment by BartG95** [comment]
@stroop566 If you want to try it yourself, here is a short guide:
* Install Python 3.4 on your system and make sure it is the only python3 version you have installed (e.g. remove other python3 installations such as Python3.7).
* Make a clone of this repository; or if you don't know how to do that: just download the zip: https://github.com/kensanata/mastodon-backup/archive/master.zip
* Start a command prompt or a powershell window as administrator.
* Make sure you are in the downloaded folder.
* (In Windows 10 you can easily open a cmd/powershell in the current folder by using the file menu on the ribbon of the explorer.)
* Within the downloaded folder, run `pip install -e .` (don't forget the dot at the end).
* (At this point you should be able to use mastodon-archive yourself.)
* Type `pip install py2exe`.
* Run `py2exe`; this should create a standalone .exe you can give to your friends or use yourself.

I haven't tested the last two points of this procedure myself; feel free to let me know if it does (not) work.

**Comment by stroop566** [comment]
@BartG95 thank you! but get some errors.
```
D:\mastodon-backup\master\mastodon-backup-master>python --version
Python 3.7.2

D:\mastodon-backup\master\mastodon-backup-master>python setup.py py2exe
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=long_description,
NameError: name 'long_description' is not defined
```
use PyInstaller
```
D:\mastodon-backup\master\mastodon-backup-master>pyinstaller --version
3.4
```
Successfully get setup.exe ，but
```
D:\mastodon-backup\master\mastodon-backup-master\output\setup>setup.exe archive kensanata@dice.camp
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
[8688] Failed to execute script setup
```
paste 'README.md' in the folder,and run:
```
D:\mastodon-backup\master\mastodon-backup-master\output\setup>setup archive kensanata@dice.camp
D:\mastodon-backup\master\mastodon-backup-master\output\setup\distutils\dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
D:\mastodon-backup\master\mastodon-backup-master\output\setup\distutils\dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
usage: setup [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup --help [cmd1 cmd2 ...]
   or: setup --help-commands
   or: setup cmd --help

error: invalid command 'archive'
```
 then I use [auto-py-to-exe](https://github.com/brentvollebregt/auto-py-to-exe),get the same error with pyinstaller.
